# Generated by Django 6.0 on 2026-06-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_closed_at_issue_closed_by_issue_resolved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolved_by',
        ),
    ]
