# Generated by Django 6.0 on 2026-05-04 14:02

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_code',
            field=models.CharField(default=organizations.models.generate_company_code, editable=False, max_length=10, unique=True),
        ),
    ]
