from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_organization_company_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organization_logos/"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="industry",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(
                blank=True,
                default=""
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.TextField(
                blank=True,
                default=""
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="state",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="timezone",
            field=models.CharField(
                blank=True,
                default="UTC",
                max_length=80
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="working_days",
            field=models.CharField(
                blank=True,
                default="Monday-Friday",
                max_length=120
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="working_hours_start",
            field=models.TimeField(
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="working_hours_end",
            field=models.TimeField(
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(
                blank=True,
                default=""
            ),
        ),
    ]
