# Generated by Django 6.0 on 2026-06-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='pro', max_length=20),
        ),
    ]
