# Generated by Django 6.0 on 2026-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('subtask_assigned', 'Subtask Assigned'), ('comment_added', 'Comment Added'), ('leave_requested', 'Leave Requested'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('company_event_created', 'Company Event Created')], max_length=50),
        ),
    ]
