# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_category_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("task_assigned", "Task Assigned"),
                    ("subtask_assigned", "Subtask Assigned"),
                    ("comment_added", "Comment Added"),
                    ("leave_requested", "Leave Requested"),
                    ("leave_approved", "Leave Approved"),
                    ("leave_rejected", "Leave Rejected"),
                    ("company_event_created", "Company Event Created"),
                    ("task_reminder", "Task Reminder"),
                    ("task_overdue", "Task Overdue"),
                    ("subtask_reminder", "Subtask Reminder"),
                    ("subtask_overdue", "Subtask Overdue"),
                    ("project_reminder", "Project Reminder"),
                    ("project_overdue", "Project Overdue"),
                    ("milestone_reminder", "Milestone Reminder"),
                    ("milestone_completed", "Milestone Completed"),
                    ("milestone_overdue", "Milestone Overdue"),
                    (
                        "welcome_organization_creator",
                        "Welcome Organization Creator",
                    ),
                    ("welcome_employee", "Welcome Employee"),
                    ("daily_digest", "Daily Digest"),
                    ("weekly_summary", "Weekly Summary"),
                    ("issue_created", "Issue Created"),
                    ("issue_assigned", "Issue Assigned"),
                ],
                max_length=50,
            ),
        ),
    ]
