# Generated by Django 6.0 on 2026-06-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_pattern',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Every Two Weeks'), ('monthly', 'Monthly'), ('first_friday', 'First Friday of Month')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='visibility',
            field=models.CharField(choices=[('organization', 'Organization'), ('private', 'Private')], default='organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('company_event', 'Company Event'), ('meeting', 'Meeting'), ('deadline', 'Deadline'), ('milestone', 'Milestone'), ('announcement', 'Announcement')], max_length=30),
        ),
    ]
