# Generated by Django 6.0 on 2026-06-03 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
        ('organizations', '0004_organization_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('personal', 'Personal Leave'), ('vacation', 'Vacation Leave'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leave_type', models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('personal', 'Personal Leave')], max_length=20)),
                ('allocated_days', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='organizations.organization')),
            ],
            options={
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
