# Generated by Django 6.0 on 2026-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(default='manual', max_length=50),
        ),
    ]
