# Generated by Django 6.0 on 2026-06-15 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_document_source_id_document_source_type'),
        ('organizations', '0006_alter_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(
    to="organizations.organization",
    on_delete=models.CASCADE,
    related_name="documents",
    null=True,
    blank=True,
),
        ),
    ]
