# Generated by Django 6.0 on 2026-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0006_alter_organization_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee')], db_index=True, default='employee', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_login'], name='accounts_us_last_lo_42da58_idx'),
        ),
    ]
