# Generated by Django 6.0 on 2026-06-10 14:31

from django.db import migrations, models


def verify_existing_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_created_at_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(verify_existing_users),
    ]
