# Generated by Django 6.0 on 2026-06-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_lead_and_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
