# Generated by Django 6.0 on 2026-05-09 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_subtask_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='subtask',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
