# Generated by Django 6.0 on 2026-05-11 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.subtask'),
        ),
    ]
