# Generated by Django 6.0 on 2026-06-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_subtask_is_overdue_task_is_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocking', to='tasks.task'),
        ),
    ]
